workdir: /spool/ml

# Лог работы приложения
log:
  path: /var/log/ml/
  level: DEBUG

ssh:
  host: 127.0.0.1
  port: 22
  user: "user"
  password: "password"
  allow_agent: false

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "traffic_arbitration"

services:
  ssp:
    host: "0.0.0.0"
    port: 8001
  dsp:
    host: "0.0.0.0"
    port: 8002
  bidder:
    host: "0.0.0.0"
    port: 8003
  stub_service:
    host: "0.0.0.0"
    port: 8004

scrapper:
  # Настройки Selenium и т.п.
  use_headless: true
  browser: "chrome"

# Другие настройки по необходимости
parallel_sources_workers: 3
parallel_categories_workers: 5
images_download_workers: 5
images_download_batch_size: 20