# Пример словаря категорий (slug -> человекочитаемое)
# По желанию можно брать из таблицы categories, или из source_info['categories'] и т.д.
CATEGORIES = {
    "general": "Новости и анонсы",
    "showbiz": "Шоу-биз",
    "sport": "Спорт",
    "crime": "Криминал",
    "cars": "Авто-мото",
    "politics": "Политика и общество",
    "army": "Армия",
    "business": "Бизнес",
    "worldwide": "В мире",
    "health": "Здоровье",
    "culture": "Культура",
    "science": "Наука и техника",
    "other": "Другие новости",
    "economic": "Экономика",
    "magic": "Предсказания",
    "accidents": "Происшествия",
    "apocalypse": "Катастрофы",
    "history": "История",
    "social": "Общество",
    "recipes": "Рецепты",
    "best": "Лучшее",
}
