"""Update articles and external_articles, add locales

Revision ID: 6a53e6bb9057
Revises: 830143884a89
Create Date: 2025-05-28 17:51:50.677153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '6a53e6bb9057'
down_revision: Union[str, None] = '830143884a89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'locales',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('code', sa.String(length=5), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code')
    )
    op.execute("INSERT INTO locales (code, name) VALUES ('ru', 'Русский'), ('en', 'English')")

    # Articles
    op.execute("UPDATE articles SET title = 'No title' WHERE title IS NULL")
    op.execute("UPDATE articles SET text = '' WHERE text IS NULL")
    op.alter_column('articles', 'title', existing_type=sa.VARCHAR(length=512), nullable=False)
    op.alter_column('articles', 'text', existing_type=sa.TEXT(), nullable=False)
    op.alter_column('articles', 'parent', new_column_name='parent_id')
    op.add_column('articles', sa.Column('external_article_id', sa.Integer(), nullable=True))
    op.add_column('articles', sa.Column('locale_id', sa.Integer(), nullable=True))  # Временно nullable
    op.execute(
        "UPDATE articles SET locale_id = (SELECT id FROM locales WHERE code = articles.locale) WHERE locale IS NOT NULL")
    op.execute("UPDATE articles SET locale_id = (SELECT id FROM locales WHERE code = 'ru') WHERE locale_id IS NULL")
    op.alter_column('articles', 'locale_id', existing_type=sa.Integer(), nullable=False)
    op.add_column('articles', sa.Column('image_id', sa.Integer(), nullable=True))
    op.add_column('articles', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    op.create_foreign_key('fk_articles_parent_id', 'articles', 'articles', ['parent_id'], ['id'])
    op.create_foreign_key('fk_articles_locale_id', 'articles', 'locales', ['locale_id'], ['id'])
    op.create_foreign_key('fk_articles_external_article_id', 'articles', 'external_articles', ['external_article_id'],
                          ['id'])
    op.create_foreign_key('fk_articles_image_id', 'articles', 'visual_content', ['image_id'], ['id'])
    op.drop_column('articles', 'locale')

    # ExternalArticles
    op.execute("UPDATE external_articles SET title = 'No title' WHERE title IS NULL")
    op.execute("UPDATE external_articles SET text = '' WHERE text IS NULL")
    op.alter_column('external_articles', 'title', existing_type=sa.VARCHAR(length=512), nullable=False)
    op.alter_column('external_articles', 'text', existing_type=sa.TEXT(), nullable=False)
    op.alter_column('external_articles', 'is_processed', existing_type=sa.BOOLEAN(), nullable=False,
                    existing_server_default=sa.text('false'))


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("UPDATE external_articles SET title = NULL WHERE title = 'No title'")
    op.execute("UPDATE external_articles SET text = NULL WHERE text = ''")
    op.alter_column('external_articles', 'is_processed', existing_type=sa.BOOLEAN(), nullable=True,
                    existing_server_default=sa.text('false'))
    op.alter_column('external_articles', 'text', existing_type=sa.TEXT(), nullable=True)
    op.alter_column('external_articles', 'title', existing_type=sa.VARCHAR(length=512), nullable=True)

    op.add_column('articles',
                  sa.Column('locale', sa.VARCHAR(length=8), server_default=sa.text("'ru'::character varying"),
                            nullable=True))
    op.execute("UPDATE articles SET locale = (SELECT code FROM locales WHERE id = articles.locale_id)")
    op.drop_constraint('fk_articles_image_id', 'articles', type_='foreignkey')
    op.drop_constraint('fk_articles_external_article_id', 'articles', type_='foreignkey')
    op.drop_constraint('fk_articles_locale_id', 'articles', type_='foreignkey')
    op.drop_constraint('fk_articles_parent_id', 'articles', type_='foreignkey')
    op.drop_column('articles', 'is_active')
    op.drop_column('articles', 'image_id')
    op.drop_column('articles', 'locale_id')
    op.drop_column('articles', 'external_article_id')
    op.alter_column('articles', 'parent_id', new_column_name='parent')
    op.execute("UPDATE articles SET title = NULL WHERE title = 'No title'")
    op.execute("UPDATE articles SET text = NULL WHERE text = ''")
    op.alter_column('articles', 'text', existing_type=sa.TEXT(), nullable=True)
    op.alter_column('articles', 'title', existing_type=sa.VARCHAR(length=512), nullable=True)
    op.drop_table('locales')
