"""Add unique constraint on visual_content.link

Revision ID: 830143884a89
Revises: 2574b436e0f2
Create Date: 2025-05-26 19:52:38.162679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '830143884a89'
down_revision: Union[str, None] = '2574b436e0f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'visual_content', ['link'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visual_content', type_='unique')
    # ### end Alembic commands ###
