"""Add is_active to ArticlePreview

Revision ID: d2f5bc19f971
Revises: 6a53e6bb9057
Create Date: 2025-07-06 16:21:01.642273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2f5bc19f971'
down_revision: Union[str, None] = '6a53e6bb9057'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles_previews', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles_previews', 'is_active')
    # ### end Alembic commands ###
